<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RyanMusicStudio.Core\RyanMusicStudio.Core.csproj" />
    <ProjectReference Include="..\RyanMusicStudio.Engine\RyanMusicStudio.Engine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
